---
title: "DA 605 - Assignment 14"
author: "Dan Fanelli"
date: "May 4, 2016"
output: pdf_document
---

# Compute the Taylor Series Expansions:

## FUNCTIONS: f(x) = 1/(1-x)

x in (-1,1)

```{r}

one_over_one_minus_x_normal <- function(x){
  return (1/(1-x))
}

one_over_one_minus_x_taylor <- function(x){
  if((x <= -1)||(x >= 1)){
    return (0)
  }
  
  answer <- 0
  for (n in 0:1000){
    answer <- answer + (x^n)
  }
  return (answer)
}
```

## TESTING: f(x) = 1/(1-x)

x in (-1,1)

```{r}
one_over_one_minus_x_normal(-0.99)
one_over_one_minus_x_taylor(-0.99)

one_over_one_minus_x_normal(-0.25)
one_over_one_minus_x_taylor(-0.25)

one_over_one_minus_x_normal(0)
one_over_one_minus_x_taylor(0)

one_over_one_minus_x_normal(0.85)
one_over_one_minus_x_taylor(0.85)

```

## FUNCTIONS: f(x) = e^x

```{r, warning=FALSE}
e_to_the_x_normal <- function(x){
  return (exp(x))
}

e_to_the_x_taylor <- function(x){
  answer <- 0
  for (n in 0:100){
    answer <- answer + (x^n)/factorial(n)
  }
  return (answer)
}
```

## TESTING: f(x) = e^x

```{r, warning=FALSE}

e_to_the_x_normal(0)
e_to_the_x_taylor(0)

e_to_the_x_normal(1)
e_to_the_x_taylor(1)

e_to_the_x_normal(8)
e_to_the_x_taylor(8)

```

## FUNCTIONS: f(x) = ln(1+x)

x in (-1,1]

```{r}
log_1_plus_x_normal <- function(x){
  if((x <= -1)||(x > 1)){
    return (0)
  }
  return (log(1+x))
}

log_1_plus_x_taylor <- function(x){
  answer <- 0
  for (n in 1:1000){
    answer <- answer + (((-1)^(n+1))*((x^n)/n))
  }
  return (answer)
}
```

## TESTING: f(x) = ln(1+x)

x in (-1,1]

```{r}

log_1_plus_x_normal(-0.99)
log_1_plus_x_taylor(-0.99)

log_1_plus_x_normal(-0.33)
log_1_plus_x_taylor(-0.33)

log_1_plus_x_normal(0)
log_1_plus_x_taylor(0)

log_1_plus_x_normal(0.5)
log_1_plus_x_taylor(0.5)

log_1_plus_x_normal(1)
log_1_plus_x_taylor(1)
```
